os: linux

language: go

go: "1.14"

install:
  - . ./.install-ninja.sh
  - go get -u golang.org/x/tools/cmd/godoc
  - go get -u github.com/tnsts/design-practice-2/build/cmd/bood

script:
  - cd $GOPATH/src/github.com/tnsts/design-practice-2/build
  - bood
  - cd ./out/bin
  - sudo chmod +x bood_rebase
  - mv bood_rebase $GOPATH/bin
  - cd $GOPATH/src/github.com/tnsts/design-practice-2/examples
  - bood_rebase
  - cat ./out/test-results/test-res.txt
