language: go

go: "1.14"

install:
  - . ./.install-ninja.sh
  - . ./.install-bood_rebase.sh
  - go get -u golang.org/x/tools/cmd/godoc

script:
  - cd $GOPATH/src/github.com/tnsts/design-practice-2/build
  - bood_rebase
  - cd ../examples/binary/out/bin/
  - sudo chmod +x bood_rebase
  - cp bood_rebase $GOPATH/src/github.com/tnsts/design-practice-2/examples/docs
  - cp bood_rebase $GOPATH/src/github.com/tnsts/design-practice-2/examples/binary
  - ls $GOPATH/bin
  - cd $GOPATH/src/github.com/tnsts/design-practice-2/examples/docs
  - ./bood_rebase
  - cd ../binary
  - ./bood_rebase
  - cat ./out/test-results/test-res.txt
