os: linux

language: go

go: "1.14"

install:
  - . ./.install-ninja.sh
  - . ./.install-bood_rebase.sh
  - go get -u golang.org/x/tools/cmd/godoc

script:
  - cd $GOPATH/src/github.com/tnsts/design-practice-2/build/out/bin
  - chmod +x bood_rebase
  - cp bood_rebase ../../
  - cd ../../
  - ./bood_rebase
