language: go

go: "1.14"

install:
  - . ./.install-ninja.sh
  - . ./.install-bood_rebase.sh
  - go get -u golang.org/x/tools/cmd/godoc

script:
  - cd $GOPATH/src/github.com/tnsts/design-practice-2/build
  - bood_rebase
  - cd $GOPATH/src/github.com/tnsts/design-practice-2/examples/binary
  - ./bood_rebase
  - cp ./out/bin/bood_rebase ../docs/
  - cd ../docs/
  - ./bood_rebase
  - cat ./out/test-results/test-res.txt
